version: '3.8'

services:
  server:
    container_name: server
    build: .
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/leslies-app
  postgres:
    container_name: db
    build:
      context: .
    depends_on:
      - postgres

volumes:
  dbdata: