--D:\leslies-app\db\schema.sql
DROP DATABASE IF EXISTS lesliesapp;
CREATE DATABASE lesliesapp;

CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE GLOBAL_LIST (
    UUID UUID PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    ARTIST VARCHAR(255) NOT NULL
);

CREATE TABLE MASTER_LIST (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    SONG_UUID UUID,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    FOREIGN KEY (SONG_UUID) REFERENCES GLOBAL_SONG_LIST (UUID) NULL,
    TITLE VARCHAR(255),
    ARTIST VARCHAR(255),
    ML_RESOURCE VARCHAR(255),
);

CREATE TABLE SETLISTS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    SETLIST_TITLE VARCHAR(255) NOT NULL,
    CREATEDON TIMESTAMP NOT NULL,
    ORDER UUID[],
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE SETLIST_SONGS (
    ID SERIAL PRIMARY KEY,
    SETLIST_ID INT NOT NULL,
    SONG_UUID UUID NOT NULL,
    FOREIGN KEY (SETLIST_ID) REFERENCES SETLISTS (ID),
    FOREIGN KEY (SONG_UUID) REFERENCES GLOBAL_SONG_LIST (UUID),
    HEADER_NOTE VARCHAR(255),
    SL_RESOURCE VARCHAR(255)
);